/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jattach_Jattach */

#ifndef _Included_jattach_Jattach
#define _Included_jattach_Jattach
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jattach_Jattach
 * Method:    exec
 * Signature: (ILjava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_jattach_Jattach_exec
  (JNIEnv *, jclass, jint, jstring, jstring, jstring, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
